name: Deploy to repo.endoy.dev

on:
  push:
    tags:
      - v*

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'
      - name: Run tests with maven
        run: mvn test

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Set up endoy repository
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'
          server-id: endoy
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Deploy package
        run: mvn deploy -DskipTests
        env:
          MAVEN_USERNAME: ${{ secrets.ENDOY_REPO_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.ENDOY_REPO_ACCESS_TOKEN }}